### this file contains cleaning functions common to all three datasets
### and lists used to generate some of the additional columns

### candy_column_selector function ###############################################
# function to select the columns needed for downstream analysis
# comments indicate which xlsx sheet does or does not contain that column
candy_column_selector <- function(candy_data){
  select_candy_data <- candy_data %>% 
    select(
      contains("timestamp", ignore.case = TRUE), #not in 2017
      contains("internal", ignore.case = TRUE), #not in 2015, 2016
      contains("old", ignore.case = TRUE),  #not in 2017
      contains(" age", ignore.case = TRUE), #not in 2015, 2016
      contains("gender", ignore.case = TRUE), #not in 2015
      contains("country", ignore.case = TRUE), #not in 2015
      contains("going", ignore.case = TRUE), #selects trick or treating all years
      contains("Q6"), #selects candy 2017
      starts_with("["), #selects candy 2015, 2016
    ) 
  return(select_candy_data)
}

#NOTES:
#may be better to select the full name of the column to be more robust
#the above does not check for column names nor does it require column names present
#if revisit consider adding testthat checks

### regex patterns for recoding country in 2016, 2017 ############################
# regex pattern to detect all usa patterns in the data
usa_pattern <- c("usa",
                 "^u[ s]",
                 "ed[\\s]{1,}st",
                 "[ast]es$",
                 "m[eu]r{1,}i[ck]a$",
                 "amer[ica]",
                 "trump",
                 "a{2,}y{4,}",
                 "alask",
                 "olina$",
                 "pi[t]{1,}s",
                 "^new[ ]{1,}[jy][oe]",
                 "^cali",
                 "^atl")

#regex pattern to detect all uk variations in the 2016 and 2017 data sets
uk_pattern <- c("u[ k]$", "[ng]dom$", "[ron][gdte]land$")

### age_corrector function #######################################################
# function to format age to a reasonable number
# set the highest age to 112 
# oldest man alive is 112, anyone older is not valid. set to NA
# ref: https://www.guinnessworldrecords.com/news/2021/6/emilio-flores-marquez-confirmed-as-the-worlds-oldest-man-living-at-112-665641
# set youngest age to >1. assume anyone younger than 1 cannot eat sweets

age_corrector <- function(age_data){
  corrected_age_data <- age_data %>% 
    mutate(
      age = case_when(
        age > 112 ~ NA_real_,
        age < 1 ~ NA_real_,
        TRUE ~ as.numeric(age)
      )
    )
  return(corrected_age_data)
}

### not_candy list ###############################################################
# list of column headings which are not edible confectionery
# generated by running the below for each year:
#     names_201X <- candy_201X_v2 %>% names()
#                    

#names across all years were compared with the following 2015, 2016 shown as eg.
#     names_2016_only <- names_2016[!names_2016 %in% names_2015]
# any additions were added to the list if they were not candy.

#This is super hard-coded. 
#If revisit think of a reproducible way to generate this list.

not_candy <- c(
  "Box’o’ Raisins", #2015
  "Box'o'Raisins", #2016, 2017
  "Chardonnay",
  "Cash, or other forms of legal tender",
  "Dental paraphenalia",
  "Generic Brand Acetaminophen",
  "Glow sticks",
  "Broken glow stick",
  "Creepy Religious comics/Chick Tracts",
  "Healthy Fruit",
  "Hugs (actual physical hugs)",
  "Kale smoothie",
  "Lapel Pins",
  "Minibags of chips",
  "JoyJoy (Mit Iodine)",
  "Mint Juleps",
  "Mint Leaves",
  "Spotted Dick",
  "Peterson Brand Sidewalk Chalk",
  "Peanut Butter Jars",
  "Trail Mix",
  "Vicodin",
  "White Bread",
  "Whole Wheat anything",
  "Person of Interest Season 3 DVD Box Set (not including Disc 4 with hilarious outtakes)",
  "Real Housewives of Orange County Season 9 Blue Ray",
  "Abstained from M&M'ing."
)
