# script to clean halloween candy data for task 4
# abraae jul 2021

# load the libraries needed
library(tidyverse)
library(janitor)
library(here)
library(readxl)
library(lubridate) 

### functions and one list used across all three files ##############################
# Note: if revisit this move these to a separate file and read in with source()

### candy_column_selector function 
# function to select the columns needed for downstream analysis
# comments indicate which xlsx sheet does or does not contain that column
candy_column_selector <- function(candy_data){
  select_candy_data <- candy_data %>% 
    select(
      contains("timestamp", ignore.case = TRUE), #not in 2017
      contains("internal", ignore.case = TRUE), #not in 2015, 2016
      contains("old", ignore.case = TRUE),  #not in 2017
      contains(" age", ignore.case = TRUE), #not in 2015, 2016
      contains("gender", ignore.case = TRUE), #not in 2015
      contains("country", ignore.case = TRUE), #not in 2015
      contains("going", ignore.case = TRUE), #selects trick or treating all years
      contains("Q6"), #selects candy 2017
      starts_with("["), #selects candy 2015, 2016
    ) 
  return(select_candy_data)
}

#NOTES:
#may be better to select the full name of the column to be more robust
#the above does not check for column names nor does it require column names present
#if revisit consider adding testthat checks

### age_corrector function 
# function to format age to a reasonable number
# set the highest age to 112 
# oldest man alive is 112, anyone older is not valid. set to NA
# ref: https://www.guinnessworldrecords.com/news/2021/6/emilio-flores-marquez-confirmed-as-the-worlds-oldest-man-living-at-112-665641
# set youngest age to >1. assume anyone younger than 1 cannot eat sweets

age_corrector <- function(age_data){
  corrected_age_data <- age_data %>% 
    mutate(
      age = case_when(
        age > 112 ~ NA_real_,
        age < 1 ~ NA_real_,
        TRUE ~ as.numeric(age)
      )
    )
  return(corrected_age_data)
}

### not_candy list 
# list of column headings which are not edible confectionery
# generated by running the below for each year:
#     names_201X <- candy_201X_v2 %>% names()
                   
# names across all years were compared with the following 2015, 2016 shown as eg.
#     names_2016_only <- names_2016[!names_2016 %in% names_2015]
# any additions were added to the list if they were not candy.

# This is super hard-coded. 
# If revisit think of a reproducible way to generate this list.

not_candy <- c(
  "Box’o’ Raisins", #2015
  "Box'o'Raisins", #2016, 2017
  "Chardonnay",
  "Cash, or other forms of legal tender",
  "Dental paraphenalia",
  "Generic Brand Acetaminophen",
  "Glow sticks",
  "Broken glow stick",
  "Creepy Religious comics/Chick Tracts",
  "Healthy Fruit",
  "Hugs (actual physical hugs)",
  "Kale smoothie",
  "Lapel Pins",
  "Minibags of chips",
  "JoyJoy (Mit Iodine)",
  "Mint Juleps",
  "Mint Leaves",
  "Spotted Dick",
  "Peterson Brand Sidewalk Chalk",
  "Peanut Butter Jars",
  "Trail Mix",
  "Vicodin",
  "White Bread",
  "Whole Wheat anything",
  "Person of Interest Season 3 DVD Box Set (not including Disc 4 with hilarious outtakes)",
  "Real Housewives of Orange County Season 9 Blue Ray",
  "Abstained from M&M'ing."
)


### First pass load the data and have a look at the data. ######################
# NOTE: do not clean_names() here
# there are punctuation marks useful for selecting candy columns downstream

candy_2015 <- read_xlsx(here::here("raw_data/boing-boing-candy-2015.xlsx")) 
glimpse(candy_2015)

candy_2016 <- read_xlsx(here::here("raw_data/boing-boing-candy-2016.xlsx")) 
glimpse(candy_2016)

candy_2017 <- read_xlsx(here::here("raw_data/boing-boing-candy-2017.xlsx")) 
glimpse(candy_2017)

### Initial thoughts ###########################################################
# * age has been classed as character for all spreadsheets.
# * age has some wild numbers in it this will need correcting.
# * the three sheets have different columns and column naming conventions.
# * note no country column for 2015.
# * some numbers in country column where age is NA for 2016 and 2017.
# * no year column for 2015, 2016 or 2017.
# * no ID column for 2015, 2016.
# * 2015 and 2016 candy columns starts with "[", 2017 starts with "Q6".
# * The trick or treating column name is very long.

### Reduce data set to columns of interest #####################################

# select only columns required for downstream analysis
# use candy_column_selector function
candy_2015_v2 <- candy_column_selector(candy_2015)
candy_2016_v2 <- candy_column_selector(candy_2016)
candy_2017_v2 <- candy_column_selector(candy_2017)

### Start cleaning 2015 ########################################################

# make id and year columns
# rename age and trick or treating columns
candy_2015_v2_2 <- candy_2015_v2 %>% 
  mutate(id = as.numeric((Timestamp)), 
         year = year(Timestamp)) %>% 
  rename("age" = "How old are you?",
         "going_trick_or_treat" = 
           "Are you going actually going trick or treating yourself?")

# make the 2015 data tidy (pivot from wide to long)
# remove the [] brackets from the candy column
# format how_old_you_are to double
candy_2015_v3 <- candy_2015_v2_2 %>% pivot_longer(
  cols = starts_with("["), 
  names_to = "candy", 
  values_to = "joy_induction") %>% 
  clean_names() %>% 
  mutate(
    candy = str_remove_all(candy, "\\[|\\]"),
    age = as.numeric(age) 
  ) 

#check for missing values 
candy_2015_v3 %>%
  summarise(across(.cols = everything(), ~sum(is.na(.x))))
# missing values found in age and joy_induction in 2015

### Start cleaning 2016 ########################################################

#follow same cleaning as for 2015

# add id and year columns and rename age and trick or treating,
# rename gender and country
candy_2016_v2_2 <- candy_2016_v2 %>% 
  mutate(id = as.numeric((Timestamp)),
         year = year(Timestamp)) %>%
  rename("age" = "How old are you?",
         "going_trick_or_treat" = 
           "Are you going actually going trick or treating yourself?",
         "gender" = "Your gender:",          
         "country" = "Which country do you live in?")

# some numbers in the country column seem to be age - possible data entry issue
# deal with these before resume cleaning for 2015 
# if age is missing a value and country is numeric, 
# the number in country will be written in the age column

#NOTE: 
#this script runs with warnings through coercing variables to be numeric or character

candy_2016_v3 <- candy_2016_v2_2 %>% 
  mutate(
    age = if_else(
      is.na(as.numeric(country)) == FALSE & is.na(age) == TRUE,
      as.numeric(country),
      as.numeric(age)),
    country = if_else(
      is.na(as.numeric(country)) == FALSE,
      NA_character_,
      as.character(country))
    )

# Make the 2016 data tidy (change from wide to long format)
# clean names, set age to numeric and country to lower case with no punctuation.
candy_2016_v4 <- candy_2016_v3 %>% pivot_longer(
  cols = starts_with(c("[", "Q6")), 
  names_to = "candy", 
  values_to = "joy_induction") %>% 
  clean_names() %>%
  mutate(
    #remove the brackets from the candy column
    candy = str_remove_all(candy, "\\[|\\]|Q6 \\| "),
    #format how_old_you_are to double
    age = as.numeric(age),
    country = str_to_lower(str_replace_all(country, "[:punct:]", ""))
  )

#check for missing values 
candy_2016_v4 %>%
  summarise(across(.cols = everything(), ~sum(is.na(.x))))
# missing values in age, gender, country and joy_induction

# Recode country column 
# for downstream analysis, recode country column to usa, canda, uk or other
# can ignore case and punctuation because these have been removed from country

# regex pattern to detect all usa patterns in the data
usa_pattern <- c("usa",
                 "^u[ s]",
                 "ed[\\s]{1,}st",
                 "[ast]es$",
                 "m[eu]r{1,}i[ck]a$",
                 "amer[ica]",
                 "trump",
                 "a{2,}y{4,}",
                 "alask",
                 "olina$",
                 "pi[t]{1,}s",
                 "^new[ ]{1,}[jy][oe]",
                 "^cali",
                 "^atl")

#regex pattern to detect all uk variations in the 2016 and 2017 data sets
uk_pattern <- c("u[ k]$", "[ng]dom$", "[ron][gdte]land$")

candy_2016_v5 <- candy_2016_v4 %>% 
  mutate(country = case_when(
    str_detect(country, "not[\\s]{1,}") ~ NA_character_,
    str_detect(country, str_c(usa_pattern, collapse = "|")) ~ "us",
    str_detect(country, str_c(uk_pattern, collapse = "|")) ~ "uk",
    str_detect(country, "^can") ~ "canada",
    is.na(country) == TRUE ~ NA_character_,
    TRUE ~ "other")
  )

### Start cleaning 2017 ########################################################

# follow same cleaning as for 2015, 2016

# add year column and rename id, age, trick or treating, gender and country
candy_2017_v3 <- candy_2017_v2 %>% 
  mutate(year = 2017) %>%  # add year column 
  rename("id" = "Internal ID",
         "age" = "Q3: AGE", 
         "going_trick_or_treat" = 
           "Q1: GOING OUT?",
         "gender" = "Q2: GENDER",
         "country" = "Q4: COUNTRY")

#some numbers in the country column seem to be age - possible data entry issue
#follow same process as for 2016

#NOTE: 
# this script runs with warnings through coercing variables to be numeric or character.
# if revisit see if there is a better way to write this.

candy_2017_v4 <- candy_2017_v3 %>% 
  mutate(
    age = if_else(
      is.na(as.numeric(country)) == FALSE & is.na(age) == TRUE,
      as.numeric(country),
      as.numeric(age)),
    country = if_else(
      is.na(as.numeric(country)) == FALSE,
      NA_character_,
      as.character(country))
    )

# Make the 2017 data tidy (change from wide to long format)
# clean names, set age to numeric and country to lower case with no punctuation.
candy_2017_v5 <- candy_2017_v4 %>% pivot_longer( 
  cols = starts_with(c("[", "Q6")), 
  names_to = "candy", 
  values_to = "joy_induction") %>% 
  clean_names() %>%
  mutate(
    #remove the brackets from the candy column
    candy = str_remove_all(candy, "\\[|\\]|Q6 \\| "),
    age = as.numeric(age),
    country = str_to_lower(str_replace_all(country, "[:punct:]", ""))
    )

# check for missing values 
candy_2017_v5 %>%
  summarise(across(.cols = everything(), ~sum(is.na(.x))))
# missing values in age, gender, country, going_trick_or_treat and joy_induction

# Recode country column 
# for downstream analysis, recode country column to usa, canda, uk or other
# use regex pattern usa_pattern, uk_pattern from 2016 clean up above
# can ignore case and punctuation because these have been removed from country

candy_2017_v6 <- candy_2017_v5 %>% 
  mutate(country = case_when(
  str_detect(country, "not[\\s]{1,}") ~ NA_character_,
  str_detect(country, str_c(usa_pattern, collapse = "|")) ~ "us",
  str_detect(country, str_c(uk_pattern, collapse = "|")) ~ "uk",
  str_detect(country, "^can") ~ "canada",
  is.na(country) == TRUE ~ NA_character_,
  TRUE ~ "other")
  )

### Final tweaks before joining the data sets ################################## 

# limit age to appropriate range for all three data sets
# use age_corrector function from cleaning_functions_task_4.R script

candy_2015_v4 <- age_corrector(candy_2015_v3)
candy_2016_v6 <- age_corrector(candy_2016_v5)
candy_2017_v7 <- age_corrector(candy_2017_v6)

# addition of confectionery column useful for analysis
#          NOTE: not_candy is a list from cleaning_functions_task_4.R
# recode NA in gender to "I'd rather not say"
# there is no gender for 2015, this has all been set to "I'd rather not say"
# correct for differences in spelling of "Box'o'Raisins

candy_2017_v8 <- candy_2017_v7 %>% 
  mutate(gender = replace_na(gender, "I'd rather not say"),
         candy = if_else(str_detect(candy, "Box’o’ Raisins"), "Box'o'Raisins", candy),
         confectionery = ! candy %in% not_candy) %>% 
  select(id, year, age, gender, country, going_trick_or_treat, 
         candy, joy_induction, confectionery)

candy_2016_v7 <- candy_2016_v6 %>% 
  mutate(gender = replace_na(gender, "I'd rather not say"),
         candy = if_else(str_detect(candy, "Box’o’ Raisins"), "Box'o'Raisins", candy),
         confectionery = ! candy %in% not_candy) %>% 
  select(id, year, age, gender, country, going_trick_or_treat, 
         candy, joy_induction, confectionery)

candy_2015_v5 <- candy_2015_v4 %>% 
  mutate(gender = "I'd rather not say",
         candy = if_else(str_detect(candy, "Box’o’ Raisins"), "Box'o'Raisins", candy),
         confectionery = ! candy %in% not_candy,
         country = NA_character_) %>% 
  select(id, year, age, gender, country, going_trick_or_treat, 
         candy, joy_induction, confectionery)

#Select rows for bind_rows
#id, year, age, gender, country, going, candy,not_conf, joy_ind
#bind 2017 first otherwise 2015 sets all missing columns to logical char types!

candy_2017_2016_2015 <- bind_rows(candy_2017_v8, candy_2016_v7, candy_2015_v5)

#write clean csv
write_csv(candy_2017_2016_2015, here::here("clean_data/clean_candy.csv"))

#clean the environment ready for analysis
rm(list=ls())